### ISSUE TITLE
Missing punc/src/aaa_inc/punc/punc.h file?

### ISSUE THREAD

**Issue by BJWiley233** [Electrostatics/FETK#53]
When I run `configure` for punc build the configure.ac file has the [line](https://github.com/Electrostatics/FETK/blob/8c293805ca5d582835b43c3d9dad4a54fb0c8f85/punc/configure.ac#L33):
```
AC_CONFIG_SRCDIR(src/aaa_inc/punc/punc.h)
```
But there is no `punc.h` file in this [directory](https://github.com/Electrostatics/FETK/tree/main/punc/src/aaa_inc/punc)

Also sorry for all the tickets.  I am preparing to install all software on MacOS since I am auditing the author of [Tinker's ](https://dasher.wustl.edu/tinker/)class, Dr. Jay Ponder this spring and most students are going to have MacOS.  

Also I am applying for the PhD program with [Dr. Houston](https://www.pure.ed.ac.uk/ws/portalfiles/portal/19933073/fetchObject.pdf) and might be nice to use APBS w.r.t. [ubiquitination to TP53 DBD](https://www.nature.com/articles/cdd201742).

**Comment by intendo** [comment]
@BJWiley233 sorry for the confusion. This repo now use CMake to build FETK and all the components. You can look at the Github Actions file, https://github.com/Electrostatics/FETK/blob/main/.github/workflows/Build.yaml, to see how you can build FETK using CMake on Windows, Mac, and Linux.
